#!/usr/bin/env bash

[ -z "$gitroot" ] && gitroot=$(git rev-parse --show-toplevel)
prefix="$gitroot/var"

cd "$gitroot/modules/sdcc"

command -v autoreconf && autoreconf -i

./configure \
  --prefix "$prefix" \
  --disable-z80-port \
  --disable-z180-port \
  --disable-r2k-port \
  --disable-r2ka-port \
  --disable-r3ka-port \
  --disable-sm83-port \
  --disable-tlcs90-port \
  --disable-ez80_z80-port \
  --disable-z80n-port \
  --disable-r800-port \
  --disable-ds390-port \
  --disable-ds400-port \
  --disable-pic14-port \
  --disable-pic16-port \
  --disable-hc08-port \
  --disable-s08-port \
  --disable-stm8-port \
  --disable-pdk13-port \
  --disable-pdk14-port \
  --disable-pdk15-port

make -j$(nproc)
make install
